### ISSUE TITLE
Documentation confusing/incomplete.

### ISSUE THREAD

**Issue by andersgs** [johnlees/seer#27]
Hi John.

Thank you for SEER, as I have mentioned offline, I think it holds great promise.

However. I think the documentation is currently letting you down, and making it frustrating for others to use SEER.

The following points could help improve it substantially, and perhaps you have already consider them.

1. Given the importance of kmer counting and the suggestion in the paper to use DSM (or fsm-lite), it is notable that there are no steps to help someone produce the necessary kmer counting files with these tools. In particular, DSM will produce multiple outputs, and yet the current documentation only mentions a single dsm_input.tx.gz file, which is confusing nomenclature (as perhaps it should be output?). Digging through the example_wrapper.py, I was able to reconstruct what might be a viable way forward.

2. The progression through the steps does not seem to have any common file names, which makes it hard to figure out what goes where. 

3. The pheno file in test folder has three columns, but two seem identical. In this on purpose? It would help if in the documentation, examples of what each file should contain were provided. 

4. It would be good to have a complete example data provided, that runs through kmer counting through to seer. I appreciate that some of the default values require larger numbers of kmers to be found. But, it would be good to have a complete case to be able to test our own implementation.

Thank you.

Best regards.

Anders.

**Comment by johnlees** [comment]
As a start, I have updated https://github.com/johnlees/seer/wiki/Usage

**Comment by johnlees** [comment]
I've added full install instructions for Ubuntu. A full worked example will follow shortly

**Comment by johnlees** [comment]
A tutorial has been added
