### ISSUE TITLE
map_back crashes with no output

### ISSUE THREAD

**Issue by mgalardini** [johnlees/seer#33]
Hi John,

sorry to bother you again with segfault reports. The following command crashes without the generation of any output:

    $ ~/software/seer/map_back -k filtered.kmers -r input.txt --threads 3
    map_back: context of significant kmers
    Reading reference sequences into memory...
    Now mapping significant kmers...
    Segmentation fault (core dumped)

The `filtered.kmers` file looks like this:

    $ head -n 5 filtered.kmers 
    TTTAGTCACCTG    0.946   6.192e-07       0.000e+00       -5.613e+00      0.000e+00
    TTCCTTCCTAATTGTAATTTTTCGTAATAATGCGATGAAAAC      0.946   2.340e-12       0.000e+00       -6.858e+00      0.000e+00
    TTCCTTCCTAATTGTAATTTTTCGTAATAATGCGATGAAAACCTGCAAAGAGTGGCT       0.653   9.494e-05       0.000e+00       -1.367e+01      0.000e+00
    TTCCTAATTGTA    0.946   2.340e-12       0.000e+00       -6.858e+00      0.000e+00
    TTAGTCACCTG     0.948   2.376e-07       0.000e+00       -5.973e+00      0.000e+00

I have tested this command with the statically linked seer v1.1.1 on Ubuntu and RHEL7.

Thank you very much for your help.

**Comment by johnlees** [comment]
Hi Marco,

Apologies for the long delay in response. 
map_back was broken at some point, it's on my to-do list to fix! Hopefully should get round to that this month.

John

**Comment by mgalardini** [comment]
Hi John,

no reason to apologies! I've followed your wiki and doing the mapping with bowtie works very well (in fact, I have the whole process in a pipeline: https://github.com/mgalardini/seer_pipeline)

Best,
Marco

**Comment by dopapo** [comment]
Dear John and dear Marco,

I had the same issue with map_back. Debugging the source code let me find out that in  significant_kmer.cpp at line 49 a blank character is assumed to be the delimiter. But seer delivers a tab delimited output  file. So changing it to '\t' works for me very well...

Cheers,
Doreen

**Comment by johnlees** [comment]
Fails build (see travis-ci) on test 7 - using filter_seer

Probably because of inconsistencies between map_back and filter_seer significant kmers?
Will fix tomorrow
