### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by OliCharity** [johnlees/seer#47]
Hi John,

The second step of kmds spits out the following:

kmds -p DT8_pairs.pheno --mds_concat subsampled_matrices.txt -o all_structure --threads 16 --write_distances

Reading subsampled matrices from subsampled_matrices.txt
Joined matrix 1
Joined matrix 2
Joined matrix 3
Joined matrix 4
Joined matrix 5
Joined matrix 6
Joined matrix 7
Joined matrix 8
Joined matrix 9
Joined matrix 10
Joined matrix 11
Joined matrix 12
Joined matrix 13
Joined matrix 14
Joined matrix 15
Joined matrix 16
Distance matrix calculated in: 0.00115613 s
terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::col(): index out of bounds
Aborted
I get a distance file, but it is empty. Not sure where I am going wrong - everything to this point gives me what I expect to be correct output.

**Comment by johnlees** [comment]
Hi,

Practically, can I suggest that you use mash instead of kmds as detailed here:
https://github.com/johnlees/seer/wiki/Using-mash-rather-than-kmds
this will be faster and easier for you!

If you'd like to stick with kmds and/or help me debug this issue, could you run 'h5ls' on one of your subsampled matrices and let me know what it returns?

**Comment by OliCharity** [comment]
Thanks John, will try mash. In the meantime h5ls on subsample 1 returns: 

dataset                  Dataset {10000, 0}

provided I have h5listed the appropriate file..

**Comment by johnlees** [comment]
Hmm, you should get {number of subsampled k-mers, number of samples}. So something must have gone wrong in the previous step.

Is your .pheno file formatted correctly? (i.e. with the sample name, matching that in the k-mer file, twice, tab-separated, followed by the phenotype – see the test/ directory for an example)

**Comment by OliCharity** [comment]
Ok. Ill run through from the top it again to be sure. .pheno file seems to be ok. 

Thanks for your help.

**Comment by OliCharity** [comment]
Hi John,

Sorry to be back asking you again - the final command of the mash section spits out the following:

$ perl R_mds.pl -d all_distances.csv -p DT8_pairs_i.pheno

"....(26 times)
Use of uninitialized value $samples[24] in sort at R_mds.pl line 72, <PHENO> line 27.
Use of uninitialized value $samples[25] in sort at R_mds.pl line 72, <PHENO> line 27.
Use of uninitialized value $samples[26] in sort at R_mds.pl line 72, <PHENO> line 27.
Number of samples in DT8_pairs_i.pheno does not match those in all_distances.csv"


but there are definitely 23 samples in the .pheno file all tab seperated:

LO1000-05_DT8_i.fasta	LO1000-05_DT8_i.fasta	DT8
SO4551-10_DT8_i.fasta	SO4551-10_DT8_i.fasta	DT8
SO8362-06_DT30_i.fasta	SO8362-06_DT30_i.fasta	DT30
SO2784-06_DT30_i.fasta	SO2784-06_DT30_i.fasta	DT30
7792_1996_DT30_i.fasta	7792_1996_DT30_i.fasta	DT30
SO2934-06_DT8_i.fasta	SO2934-06_DT8_i.fasta	DT8
SO2493-10_DT30_i.fasta	SO2493-10_DT30_i.fasta	DT30
SO5825-07_DT30_i.fasta	SO5825-07_DT30_i.fasta	DT30
SO1872-11_DT30_i.fasta	SO1872-11_DT30_i.fasta	DT30
SO2996-10_DT8_i.fasta	SO2996-10_DT8_i.fasta	DT8
LO1157-10_DT8_i.fasta	LO1157-10_DT8_i.fasta	DT8
SO2230-11_DT8_i.fasta	SO2230-11_DT8_i.fasta	DT8
SO4527-10_DT8_i.fasta	SO4527-10_DT8_i.fasta	DT8
SO3086-11_DT8_i.fasta	SO3086-11_DT8_i.fasta	DT8
SO3645-11_DT30_i.fasta	SO3645-11_DT30_i.fasta	DT30
7403_02_DT30_i.fasta	7403_02_DT30_i.fasta	DT30
6886_1997_DT30_i.fasta	6886_1997_DT30_i.fasta	DT30
103_1993_DT30_i.fasta	103_1993_DT30_i.fasta	DT30
6888_1997_DT8_i.fasta	6888_1997_DT8_i.fasta	DT8
60_03_DT8_i.fasta	60_03_DT8_i.fasta	DT8
2684_1994_DT8_i.fasta	2684_1994_DT8_i.fasta	DT8
7668_1996_DT8_i.fasta	7668_1996_DT8_i.fasta	DT8
SO4839-10_DT30_i.fasta	SO4839-10_DT30_i.fasta	DT30

and definitly 23 output distances in all_distances.csv (have converted to text file to add to comment)

[all_distances.txt](https://github.com/johnlees/seer/files/750149/all_distances.txt)

**Comment by johnlees** [comment]
Hi @OliCharity,

Sorry for the slow reply. I think this is probably due to the formatting of the .pheno file. Could you attach it here?

One thing you'll need to do is convert all the DT8 to 0 and DT30 to 1 as seer doesn't yet understand arbitrary coding of dichotomous phenotypes. You can do that with

    sed -e 's/DT8$/0/' -e 's/DT30$/1/' old.pheno > new.pheno

**Comment by OliCharity** [comment]
Hi John,

No problem. Will test, file is attached (with alterations) anyway. Thank you.
[DT8_pairs.txt](https://github.com/johnlees/seer/files/760484/DT8_pairs.txt)

**Comment by johnlees** [comment]
I think the three empty lines at the end of the file are causing this problem. If you remove them hopefully it should work.
