### ISSUE TITLE
version-1.1.3 compile issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by campy1113** [johnlees/seer#51]
src$ make CXX=/usr/bin/g++-4.9
/usr/bin/g++-4.9 -Wall -O3 -std=c++11 -I/home/campy/software/include -I../gzstream -I../dlib -I/usr/local/hdf5/include -D DLIB_NO_GUI_SUPPORT=1 -D DLIB_USE_BLAS=1 -D DLIB_USE_LAPACK=1 -DARMA_USE_HDF5=1  -c -o kmer.o kmer.cpp
In file included from /usr/local/include/armadillo:83:0,
                 from kmer.hpp:9,
                 from kmer.cpp:8:
/usr/local/include/armadillo_bits/include_hdf5.hpp:13:22: fatal error: hdf5.h: No such file or directory
     #include <hdf5.h>
                      ^
compilation terminated.
<builtin>: recipe for target 'kmer.o' failed
make: *** [kmer.o] Error 1

**Comment by johnlees** [comment]
Might be related to https://github.com/johnlees/seer/commit/7a55007cd4ecc0324529a46b10366d6a16527115

will test next week

**Comment by campy1113** [comment]
looks like it is working when replacing -I/usr/local/hdf5/include by -I/usr/include/hdf5/serial in the Makefile.
