### ISSUE TITLE
Difference between output and manual description of output

### ISSUE THREAD

**Issue by flashton2003** [johnlees/seer#52]
Hi John,

In the Usage wiki it says that the output is 

'Output columns are sequence of element, frequency in sample set, uncorrected p-value, corrected p-value, beta, standard error, p-values of covariates, comments on regression fit and optionally the samples the sequence element appears in.'

But the actual output columns are a little different (in the version running on Sanger infrastructure anyway). My main confusion is between the uncorrected p-value and corrected p-value. In the output, there are wald_p_val and lrt_p_val, with the wald_p_val consistently lower than the lrt_p_val. Is one of these multiple test corrected?

Thanks,

Phil

**Comment by johnlees** [comment]
Hi Phil,

I have updated the usage page to make this correct, and clearer. You should use the lrt_p_val; none of the p-values are multiple test corrected.

John

**Comment by flashton2003** [comment]
Thanks John. I ended up using 100 random permutations of my phenotype to estimate the LRT p-value for a false positive rate of 0.05, like in the paper.
