### ISSUE TITLE
Discrepancy in usage

### ISSUE THREAD

**Issue by flashton2003** [johnlees/seer#53]
Hi John,

Just a minor thing, but FYI the R_mds.pl script usage (when just run `perl ~/programs/seer/scripts/R_mds.pl`) says that `Usage: ./R_mds.pl -k <filtered_kmers.txt> -p <pheno_file>`

Whereas the wiki, and the usage info further down on the command line, correctly says that you give it the distance matrix and the pheno file. 

I'm using the version on the Sanger infrastructure, so maybe different from the release version.

Ta,

Phil

**Comment by johnlees** [comment]
Hi Phil,

This was fixed in e28497a814a2beb45cdf0bd659dc078838638faf

The sanger install may have been out of date, but I have updated it to master now. The version in `/nfs/users/nfs_j/jl11/installations/pangwas/scripts/R_mds.pl` is correct.

John
