### ISSUE TITLE
strange results with wald_p_val of 0 and lrt_p_val of 1

### ISSUE THREAD

**Issue by flashton2003** [johnlees/seer#55]
On a few different seer runs I have seen results that had what looked like quite unusual results to me. e.g.

![image](https://cloud.githubusercontent.com/assets/2613906/26444280/fb9c3138-4165-11e7-914c-f737d01b1f18.png)

this kmer had a significant association with one of the PCA components, and I would ignore it because of the lrt p-value and low MAF (0.009), but I'm just curious what explains the difference between the wald and lrt tests and whether these results are meant to be printed, or whether this is expected behaviour.

**Comment by johnlees** [comment]
This will be spurious due to the low MAF. The Wald test is the significance of beta divided by se, which in this case is (incorrrectly) enormous hence the 0 p-value. The LRT is more reliable, and shows the fit is not significantly different from the null model of zero beta.
