### ISSUE TITLE
PREFIX is blank, so getting -I/include etc

### ISSUE THREAD

**Issue by tseemann** [johnlees/seer#57]
#The Makefile now has:

```
# Default prefix. Can change this to system directories if needed
#PREFIX=${HOME}/software
#BINDIR=$(PREFIX)/bin
```

So getting stuff like

```
g++ -Wall -O3 -std=c++11 -I/include
```

Is this intended?

(Ironically it helps it to build on linuxbrew now!)

**Comment by johnlees** [comment]
This makes the Makefile more general (as noted in #48 by @karel-brinda), as PREFIX can be set by the user now. I think this is consistent with the GNU advice of not trying to guess these variables.

I can add `/usr/include` as a default if that helps instead, but it still builds on my test systems
