### ISSUE TITLE
Managed to compile 1.1.4 in Linuxbrew

### ISSUE THREAD

**Issue by tseemann** [johnlees/seer#59]
FYI - might not work for all, but it's worth a try!   `seer -h` does not segfault anymore.

```
brew tap tseemann/homebrew-bioinformatics-linux
brew tap homebrew/science
brew install seer
```

https://github.com/tseemann/homebrew-bioinformatics-linux/blob/master/seer.rb

**Comment by johnlees** [comment]
Cool, thanks @tseemann!
