### ISSUE TITLE
Seer: Can't stat input file: projection

### ISSUE THREAD

**Issue by cizydorczyk** [johnlees/seer#62]
Hello,

I am very much interested in applying SEER to my research. 

Unfortunately, following the tutorial (on my own data), I can get everything to run as it should up until I try to run SEER itself. When I try to run seer, I get the following error:

```
$~/Software/seer_v1.1.3/seer -k fsm_out00.gz -p 12_subsample.pheno --struct projection --threads 8 --maf 0.05 > seer00.txt
seer: sequence element enrichment analysis
Can't stat input file: projection
```
When I take a look at the projection.samples file, all it has inside is a list of my samples, but nothing else. Perhaps this is where the issue lies?

I run the command to generate the projection file like so:

```
$ perl ~/Software/seer_v1.1.3/seer-master/scripts/R_mds.pl -d all_distances.csv -p 12_subsample.pheno -o projection
Running projection
```
I get no error messages when running this command, and I have made sure to install rhdf5 using bioconductor as per tutorial instructions. Seeing that I am not getting any error messages up until running SEER, I am really not sure where the issue might be.

As such, any help in resolving this issue would be much appreciated.

Thank you,

Conrad Izydorczyk

**Comment by johnlees** [comment]
Do you have a file called 'projection'? Can you check its contents with h5ls or h5dump?

**Comment by cizydorczyk** [comment]
Thank you for your response.

The only file with 'projection' in the name is a 'projection.samples' file, which is a text file, not a hdf5 file.

No other files are produced by the 'R_mds.pl' script. Is there a file not being created that should be perhaps?

Conrad

**Comment by johnlees** [comment]
There should be a file named `projection` along with `projection.samples`, which is why the seer step is failing. I think you're right that the `R_mds.pl` script hasn't worked.

Can you edit the script to comment out line 165 so it looks like this
```
#unlink($tmp_file_name, "$tmp_file_name.Rout");
````
and then run it again, and have a look at the `mds_tmp.Rscript.Rout` file that should be produced?

John

**Comment by cizydorczyk** [comment]
The following is the output of the R_mds.pl script after commenting out line 165:

```
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rhdf5)
> distances <- read.csv("all_distances.csv", header=FALSE, stringsAsFactors=FALSE)
> projection <- cmdscale(distances, k = 10, eig = T)
Warning message:
In cmdscale(distances, k = 10, eig = T) :
  only 7 of the first 10 eigenvalues are > 0
> covariates <- projection[["points"]]
> 
> for (i in 1:10)
+ {
+    covariates[,i] <- covariates[,i]/max(abs(covariates[,i]))
+ }
Error in covariates[, i] : subscript out of bounds
Execution halted
```
If only 7 of the first 10 eigenvalues are > 0, could this be an issue due to my using a very small sample size (11 isolates) as a trial run with SEER? I eventually plan on using >150 isolates but thought for simplicity's sake I would give it a first pass with just a fraction of the isolates.

**Comment by johnlees** [comment]
Hi Conrad,

Ah yes, that will be the problem. I'd only recommend using SEER with >100 isolates, otherwise the models won't fit.
Feel free to reopen if you have any further problems.

John
