### ISSUE TITLE
Error: Degrees of freedom argument is -nan, but must be > 0

### ISSUE THREAD

**Issue by mgalardini** [johnlees/seer#64]
Hi,

once more, thanks for this fantastic approach. I encountered the following error when running `seer`on a toy example (~70 strains, kmers from a short 300bp region).

Here's the command used/output (I restricted the output to make it more readable):
```
> seer -k kmers.gz --pheno phenotypes.txt --struct test_distance.tsv --threads 5 --print_samples --no_filtering --pval 1 | awk -F'\t' '{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7}'
seer: sequence element enrichment analysis
Detected continuous phenotype
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::domain_error> >'
  what():  Error in function boost::math::students_t_distribution<double>::students_t_distribution: Degrees of freedom argument is -nan, but must be > 0 !
sequence        maf     chisq_p_val     wald_p_val      lrt_p_val       beta    se
TTTTAAGCAACTATTGACACACACATGAAGGCAAAAGCGATATTACTCGCCTCTGTCCTGCTCGTGGGTTGCCAGAGTACCGGCAACGTTCAACAGCACG    0.641   3.000e-01       1.000e+00       1.000e+00       1.123e-01       3.041e+05
TTTTAAGCAACTATTGACACACACATGAAGGCAAAAGCGATATTACTCGCCTCTGTCCTGCTCGTGGGTTGCCAGAGCACCGGCAACGTTCAACAGCACG    0.297   4.459e-01       1.000e+00       1.000e+00       -2.765e-01      2.414e+05
TTTGCTGCTTCCCCTTGACCAGCTGCAGAAAGGCTCTGTGCGTGCTGTTGAACGTTGCCGGTGCTCTGGCAACCCACGAGCAGGACAGAGGCGAGTAATA    0.297   4.459e-01       1.000e+00       1.000e+00       -2.765e-01      2.414e+05
TTTGCTGCTTCCCCTTGACCAGCTGCAGAAAGGCTCTGTGCGTGCTGTTGAACGTTGCCGGTACTCTGGCAACCCACGAGCAGGACAGAGGCGAGTAATA    0.656   6.705e-01       9.998e-01       9.998e-01       3.924e-02       1.686e+02
```

Is there anything I can do to avoid this error? Is it due to the limited size of the region I'm looking at?

Best,
Marco

**Comment by johnlees** [comment]
Hi Marco,

What version of seer are you using? This might have been fixed in ecaed1c (issue #46). If you pull the most recent version and recompile does that help?

Cheers,
John

**Comment by mgalardini** [comment]
Hi John,

I'm using version `1.2alpha4`. Unfortunately I can't compile seer on my setup (either HPC or laptop). Which precompiled release would you recommend downloading to run a test?

Best,
Marco

**Comment by johnlees** [comment]
OK, I think `1.2alpha3` and higher should be fine, so I'm not sure what's causing this error.
Would you be able to send me your input files (just the problematic k-mer lines if it's too big)?

**Comment by mgalardini** [comment]
Just sent you an email, thanks again!

**Comment by johnlees** [comment]
Can replicate this using test data. Will fix
