### ISSUE TITLE
R_mds.pl not working

### ISSUE THREAD

**Issue by samlipworth** [johnlees/seer#65]
Hi,

Everything works up until I try to run R_mds.pl.  It gives the output Running Projection but then the only output file in the directory is projection.samples, there is no file called projection..

What is wrong?

**Comment by johnlees** [comment]
Hi Sam,

Can you comment out the line near the end of R_mds.pl that starts with 'unlink' (put a '#' at the start of the line), and then run the script again. Have a look at the .Rout file that's created and see if that helps, or if nothing obvious comes up paste it as a reply here.

**Comment by samlipworth** [comment]
The only output I get is projection.samples
Output of .Rout is:
library(rhdf5)
distances <- read.csv("all_distances.csv", header=FALSE, stringsAsFactors=FALSE)
projection <- cmdscale(distances, k = 10, eig = T)
covariates <- projection[["points"]]

for (i in 1:10)
{
   covariates[,i] <- covariates[,i]/max(abs(covariates[,i]))
}

h5createFile("projection")
h5write(covariates,"projection","dataset")
H5close()

pdf("scree_plot.pdf")
plot(projection[[2]][1:30], type='l', xlab="Dimensions", ylab="Eigenvalue", main="Scree plot")
dev.off()

**Comment by johnlees** [comment]
That looks like the R script rather than log. Try running it 'R CMD BATCH <script name>' and look at the output in the .Rout file

**Comment by samlipworth** [comment]
after running it nothing appears to stdout and the only .Rout file in the directory is the one above (with the same contents in)

**Comment by johnlees** [comment]
OK, try running the commands in the script you pasted above in interactive mode in R (i.e. start R and run them one by one, pasting them in) and check the output for error messages.

If that doesn't work send me your all_distances.csv file and I'll try for you

**Comment by samlipworth** [comment]
aha it was all down to a missing R library, now installed and working fine.  Thanks.
