### ISSUE TITLE
lots assigned pval of 386 by mapping_to_phandango.pl

### ISSUE THREAD

**Issue by laurencowley** [johnlees/seer#66]
Hi John,
I have run seer but am confused because most of the p values assigned to the phandango.plot file are 386. Has something gone wrong somewhere?
Thanks!
Lauren

**Comment by johnlees** [comment]
Hi Lauren, 
Just to give a public answer: there will be p values of zero in the input, which should likely be filtered out first. I'm going to change this default to warn about these entries rather than outputting them.
Thanks,
John
