### ISSUE TITLE
Logistic and linear regression

### ISSUE THREAD

**Issue by duhuipeng** [johnlees/seer#75]
Dear author 
Hello, I'm running according to the method of an article, but I found that he did logical regression is using your method of this article, I read through your article, but I did not see this piece of code, can you provide a link, thank you! 
Looking forward to receiving your reply

**Comment by johnlees** [comment]
Most of the code for logistic regression is here: https://github.com/johnlees/seer/blob/master/src/seerBinaryAssoc.cpp

But for a simpler/more up to date version see: https://github.com/mgalardini/pyseer/blob/master/pyseer/model.py
