### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by ayixon** [johnlees/seer#76]
Afer feed the terminal with the command line: 
$ seer -k 97fsm_kmers.txt.gz  -p 97biodegradation.pheno --struct projection --threads 4 --maf 0.05 > seer00.txt
I get: 
seer: sequence element enrichment analysis
Detected binary phenotype
terminate called after throwing an instance of 'std::logic_error'
  what():  mean(): object has no elements
Aborted (core dumped)

My projection file is ok, and dependencies are installed. What is happening?

**Comment by johnlees** [comment]
Looks like the loading of some input is failing, perhaps the phenotype file? What do the input files look like?

**Comment by ayixon** [comment]
I suspect that.

The phenotype file looks like: 

cluster.1.fasta	        1
cluster.10.fasta	1
cluster.11.fasta	0
cluster.12.fasta	1
cluster.13.fasta	1
cluster.14.fasta	0
cluster.15.fasta	1

**Comment by ayixon** [comment]
Well, the problem is solved. I add a 3erd column in the pheno file and header. 
My output look like: 
sequence | maf | chisq_p_val | wald_p_val | lrt_p_val | beta | se | covar1_p | covar2_p | covar3_p | covar4_p | covar5_p | covar6_p | covar7_p | covar8_p | covar9_p | covar10_p
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
TTTTTTTGGCA | 0.536 | 4.01E-08 | 4.41E-08 | 4.41E-08 | -2.56E+01 | 4.68E+00 | 1.69E-03 | 1.78E-05 | 7.05E-04 | 8.87E-01 | 3.84E-02 | 4.45E-01 | 5.67E-01 | 3.31E-01 | 1.76E-01 | 3.20E-01

**Comment by johnlees** [comment]
Great! seer is based on the pheno format used in plink and so needs three columns.

You may also be interested in our more recent version, which is better documented: https://pyseer.readthedocs.io/en/master/
