### ISSUE TITLE
Help: Input file for combineKmers

### ISSUE THREAD

**Issue by vidhya-sai** [johnlees/seer#78]
Hi ,

I would like to know what should go as the input for the combineKmers command

`combineKmers -r 21mer_samples.txt -o all_21mers_new --min_samples 2`

What exactly should go in the 21mer_samples.txt file?  

Thankyou

**Comment by johnlees** [comment]
I'm sorry, but I no longer support this software or the `combineKmers` subcommand. 

Please use [unitig-caller](https://github.com/johnlees/unitig-caller) instead, and the [pyseer](https://github.com/mgalardini/pyseer) package for GWAS.
